---
version: '3.5'

# Start elasticsearch in Docker, for use on development environment.
#   https://hub.docker.com/_/elasticsearch
services:
  searchengine:
    # https://hub.docker.com/_/tomcat
    image: "tomcat:10.1.40-jre11"
    container_name: eatlas-searchengine
    depends_on:
      - elasticsearch
    networks:
      - eatlas
    ports:
      - "8085:8080"
    volumes:
      - ./webapps:/usr/local/tomcat/webapps
      - ./tomcat-conf:/usr/local/tomcat/conf
      - ./searchengine-data:/usr/local/tomcat/searchengine-data
    env_file:
      - "tomcat.env"

  elasticsearch:
    # https://hub.docker.com/_/elasticsearch
    #image: "elasticsearch:8.13.0"
    image: "elasticsearch:8.15.2"
    container_name: eatlas-elasticsearch
    # network_mode host: Elastic search can be access using localhost:9200 and localhost:9300
    #network_mode: host
    networks:
      - eatlas
    ports:
      # 9200: Port for HTTP requests, to index, search, etc
      - "9200:9200"

      # 9300: Port used for communication between nodes.
      #   Elastic Search runs with a single node. We do not need this port.
      #- "9300:9300"
    volumes:
      # Persistent search index files
      - ./elasticsearch-data:/usr/share/elasticsearch/data
    env_file:
      - "elasticsearch.env"

networks:
  # Same network as Drupal 7, to be able to use D10 API from D7
  eatlas:
    external: true
    name: eatlas-drupal7-network
